import { Poppins } from "next/font/google";
import "./globals.css";


import { DM_Sans } from 'next/font/google';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // choose what you need
  variable: '--font-dm-sans',
  display: 'swap',
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className="min-w-screen overflow-hidden bg-sky-50 text-gray-800 font-poppins antialiased">
        
        <main>
        {children}
        </main>
            
      </body>
    </html>
  );
}
